/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.List;
import dao.DAO_Distributor;
import javax.swing.JOptionPane;
import model.Model_distributor;
import service.Service_Distributor;
import tablemodel.TableMod_Distributor;



/**
 *
 * @author RVNOLDYVX
 */
public class MasterDistributor extends javax.swing.JPanel {

    private Service_Distributor servis = new DAO_Distributor();
    private TableMod_Distributor tblModel = new TableMod_Distributor();
    
    
    
   
    public MasterDistributor() {
        initComponents();
        
        tabel_barang.setModel(tblModel);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        JScrollPanel = new javax.swing.JScrollPane();
        tabel_barang = new custom.Tablecustom();
        jLabel2 = new javax.swing.JLabel();
        bt_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        t_cari = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tambahData = new javax.swing.JPanel();
        L_databarang2 = new javax.swing.JLabel();
        bt_tambah1 = new javax.swing.JButton();
        btn_batal1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        t_idDistributor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_NamaDistributor = new javax.swing.JTextField();
        t_Telp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t_Alamat = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabel_barang.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabel_barangAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barangMouseClicked(evt);
            }
        });
        JScrollPanel.setViewportView(tabel_barang);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Data Distributor");

        bt_tambah.setText("TAMBAH");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        t_cari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_cari.setText("Pencarian");
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_brg/pencarian 2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tampilDataLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(tampilDataLayout.createSequentialGroup()
                                .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton2))
                            .addComponent(JScrollPanel)))
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addComponent(JScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        mainPanel.add(tampilData, "card2");

        L_databarang2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        L_databarang2.setText("Tambah Data Distributor");

        bt_tambah1.setText("Tambah");
        bt_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambah1ActionPerformed(evt);
            }
        });

        btn_batal1.setText("BATAL");
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("ID Distributor");

        t_idDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idDistributorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nama Distributor");

        t_NamaDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_NamaDistributorActionPerformed(evt);
            }
        });

        t_Telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_TelpActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Telepom");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Alamat");

        t_Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_AlamatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_NamaDistributor)
                    .addComponent(t_idDistributor)
                    .addComponent(t_Alamat)
                    .addComponent(t_Telp)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 855, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_idDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(t_NamaDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_Telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(t_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahDataLayout = new javax.swing.GroupLayout(tambahData);
        tambahData.setLayout(tambahDataLayout);
        tambahDataLayout.setHorizontalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_databarang2)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addComponent(bt_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tambahDataLayout.setVerticalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahDataLayout.createSequentialGroup()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(L_databarang2)
                        .addGap(18, 18, 18)
                        .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(tambahData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tampilData);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
      
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void bt_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambah1ActionPerformed
        if(bt_tambah1.getText().equals("TAMBAH")) {
            bt_tambah1.setText("SIMPAN");
            t_idDistributor.setText(servis.nomor());
        }
        else if (bt_tambah1.getText().equals("SIMPAN")) {
            simpanData();
        }
        else if (bt_tambah1.getText().equals("PERBARUI")) {
            perbaruiData();
        }
    }//GEN-LAST:event_bt_tambah1ActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tambahData);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        bt_tambah1.setText("SIMPAN");
        t_idDistributor.setText(servis.nomor());
        t_idDistributor.setEnabled(false);
        
        
        if(bt_tambah.getText().equals("UBAH"))
        {
            dataTabel();
        }
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void tabel_barangAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabel_barangAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_barangAncestorAdded

    private void tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_barangMouseClicked
        if(bt_tambah.getText().equals("TAMBAH")) {
            bt_tambah.setText("UBAH");
        }
        btn_hapus.setVisible(true);
        btn_batal.setVisible(true);
    }//GEN-LAST:event_tabel_barangMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_NamaDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_NamaDistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_NamaDistributorActionPerformed

    private void t_idDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idDistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idDistributorActionPerformed

    private void t_TelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_TelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_TelpActionPerformed

    private void t_AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_AlamatActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPanel;
    private javax.swing.JLabel L_databarang2;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JButton bt_tambah1;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batal1;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_Alamat;
    private javax.swing.JTextField t_NamaDistributor;
    private javax.swing.JTextField t_Telp;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_idDistributor;
    private custom.Tablecustom tabel_barang;
    private javax.swing.JPanel tambahData;
    private javax.swing.JPanel tampilData;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
    btn_hapus.setVisible(false);
    btn_batal.setVisible(false);
    List<Model_distributor> list = servis.getData();
    tblModel.setData(list);
}

    private void dataTabel() {
        tampilData.setVisible(false);
        tambahData.setVisible(true);
        
        int row = tabel_barang.getSelectedRow();
        L_databarang2.setText("Perbarui Data Distributor");
        
        
        t_idDistributor.setEnabled(false);
        t_NamaDistributor.setEnabled(true);
        
        
        t_idDistributor.setText     (tabel_barang.getModel().getValueAt(row, 0).toString());
        t_NamaDistributor.setText   (tabel_barang.getModel().getValueAt(row, 1).toString());
        t_Telp.setText              (tabel_barang.getModel().getValueAt(row, 2).toString());
        t_Alamat.setText            (tabel_barang.getModel().getValueAt(row, 3).toString());
        
        
       
        bt_tambah1.setText("PERBARUI");
        btn_batal.setVisible(true);
    }

    private void hapusData() {
       int index = tabel_barang.getSelectedRow();
       if (index!=-1) {
           Model_distributor model = tblModel.getData(tabel_barang.convertRowIndexToModel(index));
           if (JOptionPane.showConfirmDialog
        (null, "Yakin data akan dihapus", "konfirmasi", JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
               servis.hapusData(model);
               tblModel.hapusData(index);
               loadData();
               resetForm();
           }
       }else{
           JOptionPane.showMessageDialog(null, "Pilih dahulu yang akan di update");
       }
    }

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new MasterDistributor());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

   
    private void aktif() {
        t_idDistributor.setVisible(true);
        t_NamaDistributor.setVisible(true);
    }

    private void simpanData() {
            if(validasiInput()==true) {      
            Model_distributor model = new Model_distributor();
            String id = t_idDistributor.getText();
            String nama_dis = t_NamaDistributor.getText();
            String telp_dis = t_Telp.getText();
            String alamat_dis = t_Alamat.getText();
            

           
            
            model.setId_distributor(id);
            model.setNama_distributor(nama_dis);
            model.setTelp_distributor(telp_dis);
            model.setAlamat_distributor(alamat_dis);                                                                                 
           
         
            servis.tambahData(model);
            tblModel.tambahData(model);
            loadData();
            resetForm();
            tampilPanel();
            bt_tambah.setText("TAMBAH");
            
        }
 
    }

    
    private void perbaruiData() {
      
        int index = tabel_barang.getSelectedRow();
        if (index != -1) {
        Model_distributor model = tblModel.getData(tabel_barang.convertRowIndexToModel(index));
        
                 
        if (validasiInput() == true) {
            String id = t_idDistributor.getText();
            String nama_dis = t_NamaDistributor.getText();
            String telp_dis = t_Telp.getText();
            String alamat_dis = t_Alamat.getText();
            
            Model_distributor model_dis = new Model_distributor();
            model.setId_distributor(id);
            model.setNama_distributor(nama_dis);
            model.setTelp_distributor(telp_dis);
            model.setAlamat_distributor(alamat_dis);      

              
                servis.perbaruiData(model);
                tblModel.perbaruiData(index,model);
                loadData();
                resetForm();
                tampilPanel();
          
        } 
    }
    }

    private boolean validasiInput() {
    boolean valid = false;
  
     if (t_idDistributor.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "Kode Jenis Barang tidak boleh kosong");
    } else if (t_NamaDistributor.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "Nama Barang tidak boleh kosong");
    } else if (t_Telp.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "Nama Barang tidak boleh kosong");
    } else if (t_Alamat.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "Nama Barang tidak boleh kosong");
   
    } else {
        valid = true;
    }
    return valid;
}


    private void resetForm() {
       bt_tambah.requestFocus();
       bt_tambah.setText("TAMBAH");       
       t_idDistributor.setText("");
       t_NamaDistributor.setText("");
       
    }

    private void pencarian() {
        List<Model_distributor> list = servis.pencarian(t_cari.getText());
        tblModel.setData(list);
    }
}
