/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DAO_pengguna;
import java.util.List;
import javax.swing.JOptionPane;
import model.Model_distributor;
import model.Model_pengguna;
import service.Service_pengguna;
import tablemodel.TableMod_Pengguna;



/**
 *
 * @author RVNOLDYVX
 */
public class MasterPengguna extends javax.swing.JPanel {

    private Service_pengguna servis = new DAO_pengguna();
    private TableMod_Pengguna tblModel = new TableMod_Pengguna();
    
    
    
   
    public MasterPengguna() {
        initComponents();
        
        tabel_barang.setModel(tblModel);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        JScrollPanel = new javax.swing.JScrollPane();
        tabel_barang = new custom.Tablecustom();
        jLabel2 = new javax.swing.JLabel();
        bt_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        t_cari = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tambahData = new javax.swing.JPanel();
        L_databarang2 = new javax.swing.JLabel();
        bt_tambah1 = new javax.swing.JButton();
        btn_batal1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_nama = new javax.swing.JTextField();
        t_username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t_telp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t_alamat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbx_level = new javax.swing.JComboBox<>();
        t_password = new javax.swing.JPasswordField();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabel_barang.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabel_barangAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barangMouseClicked(evt);
            }
        });
        JScrollPanel.setViewportView(tabel_barang);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Data Distributor");

        bt_tambah.setText("TAMBAH");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        t_cari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_cari.setText("Pencarian");
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_brg/pencarian 2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tampilDataLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(tampilDataLayout.createSequentialGroup()
                                .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton2))
                            .addComponent(JScrollPanel)))
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addComponent(JScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        mainPanel.add(tampilData, "card2");

        L_databarang2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        L_databarang2.setText("Tambah Data Pengguna");

        bt_tambah1.setText("Tambah");
        bt_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambah1ActionPerformed(evt);
            }
        });

        btn_batal1.setText("BATAL");
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("ID ");

        t_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nama ");

        t_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaActionPerformed(evt);
            }
        });

        t_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usernameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Username");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Password");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Telepon");

        t_telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_telpActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Alamat");

        t_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_alamatActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Level");

        cbx_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Akses -", "Owner", "User", " " }));

        t_password.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_nama)
                    .addComponent(t_id)
                    .addComponent(t_username)
                    .addComponent(t_alamat)
                    .addComponent(t_telp)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(t_password))
                .addContainerGap())
            .addComponent(cbx_level, 0, 935, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(t_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(cbx_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahDataLayout = new javax.swing.GroupLayout(tambahData);
        tambahData.setLayout(tambahDataLayout);
        tambahDataLayout.setHorizontalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_databarang2)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addComponent(bt_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        tambahDataLayout.setVerticalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahDataLayout.createSequentialGroup()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(L_databarang2)
                        .addGap(18, 18, 18)
                        .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(tambahData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tampilData);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
      
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void bt_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambah1ActionPerformed
        if(bt_tambah1.getText().equals("TAMBAH")) {
           bt_tambah1.setText("SIMPAN");
           t_id.setText(servis.nomor());
        }
        else if (bt_tambah1.getText().equals("SIMPAN")) {
            simpanData();
        }
        else if (bt_tambah1.getText().equals("PERBARUI")) {
            perbaruiData();
        }
    }//GEN-LAST:event_bt_tambah1ActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tambahData);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        bt_tambah1.setText("SIMPAN");
        t_id.setText(servis.nomor());
        t_id.setEnabled(false);
        
        
        if(bt_tambah.getText().equals("UBAH"))
        {
            dataTabel();
        }
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void tabel_barangAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabel_barangAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_barangAncestorAdded

    private void tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_barangMouseClicked
        if(bt_tambah.getText().equals("TAMBAH")) {
            bt_tambah.setText("UBAH");
        }
        btn_hapus.setVisible(true);
        btn_batal.setVisible(true);
    }//GEN-LAST:event_tabel_barangMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaActionPerformed

    private void t_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idActionPerformed

    private void t_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_usernameActionPerformed

    private void t_telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_telpActionPerformed

    private void t_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_alamatActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPanel;
    private javax.swing.JLabel L_databarang2;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JButton bt_tambah1;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batal1;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JComboBox<String> cbx_level;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_alamat;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_nama;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JTextField t_telp;
    private javax.swing.JTextField t_username;
    private custom.Tablecustom tabel_barang;
    private javax.swing.JPanel tambahData;
    private javax.swing.JPanel tampilData;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
    btn_hapus.setVisible(false);
    btn_batal.setVisible(false);
    List<Model_pengguna> list = servis.getData();
    tblModel.setData(list);
}

    private void dataTabel() {
        tampilData.setVisible(false);
        tambahData.setVisible(true);
        
        int row = tabel_barang.getSelectedRow();
        L_databarang2.setText("Perbarui Data Distributor");
        
        
        t_id.setEnabled(false);
        t_nama.setEnabled(true);
        
        
        t_id.setText     (tabel_barang.getModel().getValueAt(row, 0).toString());
        t_nama.setText   (tabel_barang.getModel().getValueAt(row, 1).toString());
        t_username.setText              (tabel_barang.getModel().getValueAt(row, 2).toString());
        t_password.setText            (tabel_barang.getModel().getValueAt(row, 3).toString());
        
        
       
        bt_tambah1.setText("PERBARUI");
        btn_batal.setVisible(true);
    }

    private void hapusData() {
       int index = tabel_barang.getSelectedRow();
       if (index!=-1) {
           Model_pengguna model = tblModel.getData(tabel_barang.convertRowIndexToModel(index));
           if (JOptionPane.showConfirmDialog
        (null, "Yakin data akan dihapus", "konfirmasi", JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
               servis.hapusData(model);
               tblModel.hapusData(index);
               loadData();
               resetForm();
           }
       }else{
           JOptionPane.showMessageDialog(null, "Pilih dahulu yang akan di update");
       }
    }

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new MasterPengguna());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

   
    private void aktif() {
        t_id.setVisible(true);
        t_nama.setVisible(true);
    }

    private void simpanData() {
            if(validasiInput()==true) {      
            
            String ID = t_id.getText();
            String nama = t_nama.getText();
            String username = t_username.getText();
            String password = t_password.getText();
            String telepon = t_telp.getText();
            String alamat = t_alamat.getText();
            String level = cbx_level.getSelectedItem().toString();
            
            Model_pengguna model = new Model_pengguna();
            model.setId_pengguna(ID);
            model.setNama_pengguna(nama);
            model.setUsername(username);
            model.setPassword(password);
            model.setTelp_pengguna(telepon);
            model.setAlamat_pengguna(alamat);
            model.setLevel(level);
         
            servis.tambahData(model);
            tblModel.tambahData(model);
            loadData();
            resetForm();
            tampilPanel();
            bt_tambah.setText("TAMBAH");
            
        }
 
    }

    
    private void perbaruiData() {
      
        int index = tabel_barang.getSelectedRow();
        if (index != -1) {
        Model_pengguna mod_pen= tblModel.getData(tabel_barang.convertRowIndexToModel(index));
        
                 
        if (validasiInput() == true) {
            String ID = t_id.getText();
            String nama = t_nama.getText();
            String username = t_username.getText();
            //String password = t_password.getText();
            String telepon = t_telp.getText();
            String alamat = t_alamat.getText();
            String level = cbx_level.getSelectedItem().toString();
            
            Model_pengguna model = new Model_pengguna();
            model.setId_pengguna(ID);
            model.setNama_pengguna(nama);
            model.setUsername(username);
            //model.setPassword(password);
            model.setTelp_pengguna(telepon);
            model.setAlamat_pengguna(alamat);
            model.setLevel(level);
                

              
                servis.perbaruiData(model);
                tblModel.perbaruiData(index,model);
                loadData();
                resetForm();
                tampilPanel();
          
        } 
    }
    }

    private boolean validasiInput() {
    boolean valid = false;
  
     if (t_id.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "ID tidak boleh kosong");
    } else if (t_nama.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "Nama tidak boleh kosong");
    } else if (t_username.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "Username tidak boleh kosong");
    }  else if (t_username.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "passwordtidak boleh kosong");
    } else if (t_username.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "Telepom tidak boleh kosong");
    }else if (t_password.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "Alamat tidak boleh kosong");
   } else if (t_username.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "LevelBarang tidak boleh kosong");
    } else {
        valid = true;
    }
    return valid;
}


    private void resetForm() {
       bt_tambah.requestFocus();
       bt_tambah.setText("TAMBAH");       
       t_id.setText("");
       t_nama.setText("");
       
    }

    private void pencarian() {
        List<Model_pengguna> list = servis.pencarian(t_cari.getText());
        tblModel.setData(list);
    }
}
