
package view;

import java.util.List;
import dao.DAO_Barang;
import dao.DAO_DetPemesanan;
import dao.DAO_Pemesanan;
import javax.swing.JOptionPane;
import model.Model_pemesanan;
import service.Service_DetPemesanan;
import service.Service_Pemesanan;
import tablemodel.TableMod_DetPemesanan;
import tablemodel.TableMod_Pemesanan;
import tablemodel.TableMod_SemPemesanan;





/**
 *
 * @author RVNOLDYVX
 */
    public class Transaksi_Pemesanan extends javax.swing.JPanel {

    private Service_Pemesanan servis_psn = new DAO_Pemesanan();
    private Service_DetPemesanan servis_det= new DAO_DetPemesanan();
    private Service_DetPemesanan servis_sem= new DAO_DetPemesanan();
     
    private TableMod_Pemesanan tblModel_psn = new TableMod_Pemesanan();
    private TableMod_DetPemesanan tblModel_det = new TableMod_DetPemesanan();
    private TableMod_SemPemesanan tblModel_sem= new TableMod_SemPemesanan();
    
     
    public Transaksi_Pemesanan() {
        initComponents();
        
        tabel_barang.setModel(tblModel_psn);
        tabel_detail.setModel(tblModel_det);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tambahData = new javax.swing.JPanel();
        L_databarang2 = new javax.swing.JLabel();
        bt_tambah1 = new javax.swing.JButton();
        btn_batal1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pn_pemesanan = new javax.swing.JPanel();
        t_noPesan = new javax.swing.JLabel();
        t_kodeBarang = new javax.swing.JTextField();
        t_tanggalPesan = new javax.swing.JLabel();
        t_kodeBarang1 = new javax.swing.JTextField();
        pn_barang = new javax.swing.JPanel();
        t_idDistributor1 = new javax.swing.JTextField();
        t_tanggalPesan2 = new javax.swing.JLabel();
        btn_distributor1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        t_noPesan3 = new javax.swing.JLabel();
        t_noPesan4 = new javax.swing.JLabel();
        t_tanggalPesan3 = new javax.swing.JLabel();
        t_namaDistributor2 = new javax.swing.JTextField();
        t_tanggalPesan4 = new javax.swing.JLabel();
        t_namaDistributor3 = new javax.swing.JTextField();
        t_tanggalPesan5 = new javax.swing.JLabel();
        t_namaDistributor4 = new javax.swing.JTextField();
        t_tanggalPesan6 = new javax.swing.JLabel();
        t_namaDistributor5 = new javax.swing.JTextField();
        t_tanggalPesan7 = new javax.swing.JLabel();
        t_namaDistributor6 = new javax.swing.JTextField();
        t_idDistributor2 = new javax.swing.JTextField();
        pn_distributor = new javax.swing.JPanel();
        t_idDistributor = new javax.swing.JTextField();
        t_tanggalPesan1 = new javax.swing.JLabel();
        t_namaDistributor = new javax.swing.JTextField();
        btn_distributor = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        t_noPesan1 = new javax.swing.JLabel();
        t_noPesan2 = new javax.swing.JLabel();
        tampilData = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_barang = new custom.Tablecustom();
        jLabel2 = new javax.swing.JLabel();
        bt_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        t_cari = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        pn_detail = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_detail = new custom.Tablecustom();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        L_databarang2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        L_databarang2.setText("Tambah Pemesanan Barang");

        bt_tambah1.setText("Tambah");
        bt_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambah1ActionPerformed(evt);
            }
        });

        btn_batal1.setText("BATAL");
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pn_pemesanan.setBackground(new java.awt.Color(0, 51, 204));

        t_noPesan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_noPesan.setForeground(new java.awt.Color(255, 255, 255));
        t_noPesan.setText("No Pemesanan");

        t_kodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_kodeBarangActionPerformed(evt);
            }
        });

        t_tanggalPesan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_tanggalPesan.setForeground(new java.awt.Color(255, 255, 255));
        t_tanggalPesan.setText("Tanggal");

        t_kodeBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_kodeBarang1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_pemesananLayout = new javax.swing.GroupLayout(pn_pemesanan);
        pn_pemesanan.setLayout(pn_pemesananLayout);
        pn_pemesananLayout.setHorizontalGroup(
            pn_pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pemesananLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pn_pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_noPesan))
                .addGap(24, 24, 24)
                .addGroup(pn_pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_pemesananLayout.createSequentialGroup()
                        .addComponent(t_tanggalPesan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(t_kodeBarang1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_pemesananLayout.setVerticalGroup(
            pn_pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pemesananLayout.createSequentialGroup()
                .addGroup(pn_pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_noPesan)
                    .addComponent(t_tanggalPesan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_kodeBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        t_idDistributor1.setText(" ");
        t_idDistributor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idDistributor1ActionPerformed(evt);
            }
        });

        t_tanggalPesan2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_tanggalPesan2.setText("Nama Distributor");

        btn_distributor1.setText("...");
        btn_distributor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_distributor1ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 51, 204));
        jPanel6.setForeground(new java.awt.Color(0, 0, 0));

        t_noPesan3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_noPesan3.setForeground(new java.awt.Color(255, 255, 255));
        t_noPesan3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t_noPesan3.setText("Barang");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t_noPesan3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t_noPesan3)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        t_noPesan4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_noPesan4.setText("Kode Barang");

        t_tanggalPesan3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_tanggalPesan3.setText("Nama Barang");

        t_namaDistributor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaDistributor2ActionPerformed(evt);
            }
        });

        t_tanggalPesan4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_tanggalPesan4.setText("Satuan");

        t_namaDistributor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaDistributor3ActionPerformed(evt);
            }
        });

        t_tanggalPesan5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_tanggalPesan5.setText("Harga");

        t_namaDistributor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaDistributor4ActionPerformed(evt);
            }
        });

        t_tanggalPesan6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_tanggalPesan6.setText("Jumlah");

        t_namaDistributor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaDistributor5ActionPerformed(evt);
            }
        });

        t_tanggalPesan7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_tanggalPesan7.setText("Subtotal");

        t_namaDistributor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaDistributor6ActionPerformed(evt);
            }
        });

        t_idDistributor2.setText(" ");
        t_idDistributor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idDistributor2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_barangLayout = new javax.swing.GroupLayout(pn_barang);
        pn_barang.setLayout(pn_barangLayout);
        pn_barangLayout.setHorizontalGroup(
            pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_barangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_barangLayout.createSequentialGroup()
                        .addComponent(t_idDistributor1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_idDistributor2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_distributor1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_barangLayout.createSequentialGroup()
                        .addComponent(t_noPesan4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(t_tanggalPesan2)
                        .addGap(76, 76, 76))
                    .addGroup(pn_barangLayout.createSequentialGroup()
                        .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_tanggalPesan3)
                            .addComponent(t_tanggalPesan4)
                            .addComponent(t_tanggalPesan5)
                            .addComponent(t_tanggalPesan6)
                            .addComponent(t_tanggalPesan7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_barangLayout.createSequentialGroup()
                        .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_namaDistributor2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_namaDistributor3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_namaDistributor4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_namaDistributor5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_namaDistributor6))
                        .addContainerGap())))
        );
        pn_barangLayout.setVerticalGroup(
            pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_barangLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_tanggalPesan2)
                    .addComponent(t_noPesan4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_idDistributor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_distributor1)
                    .addComponent(t_idDistributor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_tanggalPesan3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaDistributor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_tanggalPesan4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaDistributor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_tanggalPesan5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaDistributor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_tanggalPesan6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaDistributor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_tanggalPesan7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaDistributor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        t_idDistributor.setText(" ");
        t_idDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idDistributorActionPerformed(evt);
            }
        });

        t_tanggalPesan1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_tanggalPesan1.setText("Nama Distributor");

        t_namaDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaDistributorActionPerformed(evt);
            }
        });

        btn_distributor.setText("...");
        btn_distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_distributorActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 51, 204));

        t_noPesan1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_noPesan1.setForeground(new java.awt.Color(255, 255, 255));
        t_noPesan1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        t_noPesan1.setText("ID Distributor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t_noPesan1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t_noPesan1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        t_noPesan2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_noPesan2.setText("ID Distributor");

        javax.swing.GroupLayout pn_distributorLayout = new javax.swing.GroupLayout(pn_distributor);
        pn_distributor.setLayout(pn_distributorLayout);
        pn_distributorLayout.setHorizontalGroup(
            pn_distributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_distributorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_distributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_distributorLayout.createSequentialGroup()
                        .addComponent(t_noPesan2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn_distributorLayout.createSequentialGroup()
                        .addComponent(t_idDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pn_distributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_namaDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_distributorLayout.createSequentialGroup()
                        .addComponent(t_tanggalPesan1)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        pn_distributorLayout.setVerticalGroup(
            pn_distributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_distributorLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_distributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_noPesan2)
                    .addComponent(t_tanggalPesan1))
                .addGap(18, 18, 18)
                .addGroup(pn_distributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_namaDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_idDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_distributor))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pn_pemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pn_distributor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pn_pemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_distributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahDataLayout = new javax.swing.GroupLayout(tambahData);
        tambahData.setLayout(tambahDataLayout);
        tambahDataLayout.setHorizontalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_databarang2)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(bt_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        tambahDataLayout.setVerticalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_databarang2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        mainPanel.add(tambahData, "card2");

        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_barang);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Data Pemesanan Barang");

        bt_tambah.setText("TAMBAH");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        t_cari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_cari.setText("Pencarian");
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_brg/pencarian 2.png"))); // NOI18N
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        tabel_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_detail);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("Data Pemesanan Barang");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("x");

        javax.swing.GroupLayout pn_detailLayout = new javax.swing.GroupLayout(pn_detail);
        pn_detail.setLayout(pn_detailLayout);
        pn_detailLayout.setHorizontalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15))))
        );
        pn_detailLayout.setVerticalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_detailLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tampilDataLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tampilDataLayout.createSequentialGroup()
                        .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_search)))
                .addGap(9, 9, 9))
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_search, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        mainPanel.add(tampilData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tampilData);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
      
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void bt_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambah1ActionPerformed
        if(bt_tambah1.getText().equals("TAMBAH")) {
            bt_tambah1.setText("SIMPAN");
            t_kodeBarang.setText(servis.nomor());
        }
        else if (bt_tambah1.getText().equals("SIMPAN")) {
            //simpanData();
        }
        else if (bt_tambah1.getText().equals("PERBARUI")) {
            //perbaruiData();
        }
    }//GEN-LAST:event_bt_tambah1ActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tambahData);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        bt_tambah1.setText("SIMPAN");
        bt_jenisBarang.setEnabled(true);
        t_kodeBarang.setEnabled(false);
        t_kodeBarang.setText(servis.nomor());
        
        if(bt_tambah.getText().equals("UBAH"))
        {
            dataTabel();
        }
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void t_kodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_kodeBarangActionPerformed

    private void tabel_barangAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabel_barangAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_barangAncestorAdded

    private void tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_barangMouseClicked
       int row = tabel_barang.getSelectedRow();
       String id = tabel_barang.getValueAt(row, 0).toString();

       pn_detail.setVisible(true);
        List<Model_Detpemesanan> list = servis_det.getData();
        tblModel_psn.setData(list);
    }//GEN-LAST:event_tabel_barangMouseClicked

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_searchActionPerformed

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        //pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_kodeBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kodeBarang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_kodeBarang1ActionPerformed

    private void btn_distributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_distributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_distributorActionPerformed

    private void t_idDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idDistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idDistributorActionPerformed

    private void t_namaDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaDistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaDistributorActionPerformed

    private void t_idDistributor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idDistributor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idDistributor1ActionPerformed

    private void btn_distributor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_distributor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_distributor1ActionPerformed

    private void t_namaDistributor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaDistributor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaDistributor2ActionPerformed

    private void t_namaDistributor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaDistributor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaDistributor3ActionPerformed

    private void t_namaDistributor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaDistributor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaDistributor4ActionPerformed

    private void t_namaDistributor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaDistributor5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaDistributor5ActionPerformed

    private void t_namaDistributor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaDistributor6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaDistributor6ActionPerformed

    private void t_idDistributor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idDistributor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idDistributor2ActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_databarang2;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JButton bt_tambah1;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batal1;
    private javax.swing.JButton btn_distributor;
    private javax.swing.JButton btn_distributor1;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_barang;
    private javax.swing.JPanel pn_detail;
    private javax.swing.JPanel pn_distributor;
    private javax.swing.JPanel pn_pemesanan;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_idDistributor;
    private javax.swing.JTextField t_idDistributor1;
    private javax.swing.JTextField t_idDistributor2;
    private javax.swing.JTextField t_kodeBarang;
    private javax.swing.JTextField t_kodeBarang1;
    private javax.swing.JTextField t_namaDistributor;
    private javax.swing.JTextField t_namaDistributor2;
    private javax.swing.JTextField t_namaDistributor3;
    private javax.swing.JTextField t_namaDistributor4;
    private javax.swing.JTextField t_namaDistributor5;
    private javax.swing.JTextField t_namaDistributor6;
    private javax.swing.JLabel t_noPesan;
    private javax.swing.JLabel t_noPesan1;
    private javax.swing.JLabel t_noPesan2;
    private javax.swing.JLabel t_noPesan3;
    private javax.swing.JLabel t_noPesan4;
    private javax.swing.JLabel t_tanggalPesan;
    private javax.swing.JLabel t_tanggalPesan1;
    private javax.swing.JLabel t_tanggalPesan2;
    private javax.swing.JLabel t_tanggalPesan3;
    private javax.swing.JLabel t_tanggalPesan4;
    private javax.swing.JLabel t_tanggalPesan5;
    private javax.swing.JLabel t_tanggalPesan6;
    private javax.swing.JLabel t_tanggalPesan7;
    private custom.Tablecustom tabel_barang;
    private custom.Tablecustom tabel_detail;
    private javax.swing.JPanel tambahData;
    private javax.swing.JPanel tampilData;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
    btn_hapus.setVisible(false);
    btn_batal.setVisible(false);
    List<Model_pemesanan> list = servis_psn.getData();
    tblModel_psn.setData(list);
    
}

    private void dataTabel() {
        tampilData.setVisible(true);
        tambahData.setVisible(true);
        
        int row = tabel_barang.getSelectedRow();
        L_databarang2.setText("Perbarui data barang");
        
        t_kodeBarang.setEnabled(false);
        //t_kodejenisbarang.setEnabled(true);
        t_namajenisbarang.setEnabled(true);
        
        t_kodeBarang.setText        (tabel_barang.getModel().getValueAt(row, 1).toString());
        t_kodejenisbarang.setText   (tabel_barang.getModel().getValueAt(row, 2).toString());
        t_namajenisbarang.setText   (tabel_barang.getModel().getValueAt(row, 3).toString());
        t_namabarang.setText        (tabel_barang.getModel().getValueAt(row, 4).toString());
        cbx_satuan.setSelectedItem  (tabel_barang.getModel().getValueAt(row, 5).toString());
        t_harga.setText             (tabel_barang.getModel().getValueAt(row, 6).toString());
        t_stok.setText              (tabel_barang.getModel().getValueAt(row, 7).toString());
        
        aktif();
        bt_tambah1.setText("PERBARUI");
        btn_batal.setVisible(true);
    }


    private void hapusData() {
       int index = tabel_barang.getSelectedRow();
       if (index!=-1) {
           Model_Pemesanan brg = tblModel_psn.getData(tabel_barang.convertRowIndexToModel(index));
           if (JOptionPane.showConfirmDialog
        (null, "Yakin data akan dihapus", "konfirmasi", JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
               servis_psn.hapusData(brg);
               tblModel_psn.hapusData(index);
               loadData();
               resetForm();
           }
       }else{
           JOptionPane.showMessageDialog(null, "Pilih dahulu yang akan di update");
       }
    }

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Transaksi_Pemesanan());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

   
    
    private void aktif() {
        t_namabarang.setEnabled(true);   
        cbx_satuan.setEnabled(true);
        t_harga.setEnabled(true);
        t_stok.setEnabled(true);
    }

   // private void simpanData() {
          if(validasiInput()==true) {
            String kode_Barang = t_kodeBarang.getText();                                                                                         
            String kode_jenis = t_kodejenisbarang.getText();
            String nama_jenisbarang = t_namajenisbarang.getText();
            String nama_barang = t_namabarang.getText();
            String satuan = cbx_satuan.getSelectedItem().toString();
            Long  harga = Long.parseLong(t_harga.getText());
            int stok = Integer.parseInt(t_stok.getText()); 
            
            Model_barang brg = new Model_barang();
            Model_jenis_barang jbr = new Model_jenis_barang();
            
            brg.setKode_Barang(kode_Barang);
            jbr.setKode_jenis(kode_jenis);
            jbr.setNama_jenis(kode_jenis);
            brg.setNama_barang(nama_barang);
            brg.setSatuan(satuan);
            brg.setHarga(harga);
            brg.setStok(stok);
            
            brg.setJns_barang(jbr);
            servis.tambahData(brg);
            tblModel.tambahData( brg);
            loadData();
            resetForm();
            tampilPanel();
            bt_tambah.setText("TAMBAH");
            
        }
    }    
    private void perbaruiData() {
      
            int index = tabel_barang.getSelectedRow();
            if (index != -1) {
            Model_barang mobar = tblModel.getData(tabel_barang.convertRowIndexToModel(index));

        if (validasiInput() == true) {
            String kode_barang = t_kodeBarang.getText();
            String kode_jenis = t_kodejenisbarang.getText();
            String nama_jenis = t_namajenisbarang.getText();
            String nama_barang = t_namabarang.getText();
            String satuan = cbx_satuan.getSelectedItem().toString();
            long harga = Long.parseLong(t_harga.getText());
            int stok = Integer.parseInt(t_stok.getText());

            Model_barang brg = new Model_barang();
            Model_jenis_barang jbr = new Model_jenis_barang();

            jbr.setKode_jenis(kode_jenis);
            jbr.setNama_jenis(nama_jenis);

            brg.setKode_Barang(kode_barang);
            brg.setNama_barang(nama_barang);
            brg.setSatuan(satuan);
            brg.setHarga(harga);
            brg.setStok(stok);
            brg.setJns_barang(jbr);

            
            servis.perbaruiData(brg);
            tblModel.perbaruiData(index, mobar);
            loadData();
            resetForm();
            tampilPanel();
        }
    }


        
    }

    private boolean validasiInput() {
    boolean valid = false;
    if (t_kodeBarang.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "Kode Barang tidak boleh kosong");
    } else if (t_kodejenisbarang.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "Kode Jenis Barang tidak boleh kosong");
    } else if (t_namajenisbarang.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "Nama Barang tidak boleh kosong");
    } else if (cbx_satuan.getSelectedItem().equals(null)) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "Satuan tidak boleh kosong");
    } else if (t_harga.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "Harga tidak boleh kosong");
    } else if (t_stok.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(javax.swing.JOptionPane.getRootFrame(), "Stok tidak boleh kosong");
    } else {
        valid = true;
    }
    return valid;
}


    private void resetForm() {
       bt_tambah.requestFocus();
       bt_tambah.setText("TAMBAH");
       t_kodeBarang.setText("");
       t_kodejenisbarang.setText("");
       t_namajenisbarang.setText("");
       t_namabarang.setText("");
       cbx_satuan.setSelectedItem(0);
       t_harga.setText("");
       t_stok.setText("");
    }

    private void pencarian() {
        List<Model_barang> list = servis.pencarian(t_cari.getText());
        tblModel.setData(list);
    }
}